version: "3"
services:
  app:
    build: ./
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - "db"
  db:
    image: mysql
    command: --init-file /var/lib/msql/init.sql
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/var/lib/msql/init.sql